spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.12:3306/viajes?serverTimezone=UTC
    username: user1
    password: user1
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.12:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: 192.168.1.12
    non-secure-port: ${server.port}

server:
  port: ${SERVER_PORT:8600}
springdoc:
  packagesToScan: com.curso.controller
  pathsToMatch: /**
